### PR TITLE
update dependencies removing all vulnerabilities

### PR DESCRIPTION
**Pull request by chriswhong**
- Updates dependencies, removing all vulnerabilities identified by npm (mosly in `lerna` and `webpack`)
- Ensures that both webpack commands work to develop and build the repl app. (the dev server and the production build)
- Updates one test and a few snapshots.

### CODE REVIEW

**Review by AndrewSepic — COMMENTED** [review]
@chriswhong  I'm getting the following error when I run `npm run build-repl` locally 

```
ERROR in main
Module not found: Error: Can't resolve './src' in '/Users/andrewsepic/mapbox-repos/jsxtreme-markdown'
resolve './src' in '/Users/andrewsepic/mapbox-repos/jsxtreme-markdown'
  using description file: /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/src.wasm doesn't exist
      as directory
        /Users/andrewsepic/mapbox-repos/jsxtreme-markdown/src doesn't exist

webpack 5.89.0 compiled with 1 error in 248 ms
``` 

Did you receive anything similar on your end?  Any thoughts?

**Comment by chriswhong** [comment]
WOMM.  Are you running this from the root of the repo?

**Comment by AndrewSepic** [comment]
Yes,  running the command from the root of the repo.  👍

**Review by AndrewSepic — APPROVED** [review]
Looks good.  Thanks

**Pull request merged**
